project_id = "uxrgnwsdkkjrueoqozuq"

[functions.mcp]
verify_jwt = false


[functions.whatsapp-notification]
verify_jwt = false

[functions.fonnte-get-groups]
verify_jwt = true

[functions.fonnte-update-group]
verify_jwt = true