// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-patients.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.23.8";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.52.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-patients.ts
var list_patients_default = defineTool({
  name: "list_patients",
  title: "Daftar pasien clinical pathway",
  description: "List clinical pathway patient records, optionally filtered by year, month, pathway type, ward, or patient name / medical record number.",
  inputSchema: {
    year: z.number().int().optional().describe("Filter by admission year, e.g. 2026."),
    month: z.number().int().optional().describe("Filter by admission month 1-12 (requires year)."),
    pathway_type: z.string().optional().describe("Exact jenis clinical pathway, e.g. 'Intracranial Hemorrhagia'."),
    ward: z.string().optional().describe("Exact bangsal / ward name."),
    search: z.string().optional().describe("Partial match on patient name or medical record number (no_rm)."),
    limit: z.number().int().optional().describe("Max rows to return, default 50, capped at 200.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ year, month, pathway_type, ward, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const take = Math.min(Math.max(limit ?? 50, 1), 200);
    let query = supabase.from("clinical_pathways").select("id, no_rm, nama_pasien, jenis_clinical_pathway, bangsal, dpjp, tanggal_masuk, tanggal_keluar, los_hari, keterangan").order("tanggal_masuk", { ascending: false }).limit(take);
    if (year) {
      const from = month ? `${year}-${String(month).padStart(2, "0")}-01` : `${year}-01-01`;
      const toDate = month ? new Date(Date.UTC(month === 12 ? year + 1 : year, month === 12 ? 0 : month, 1)) : new Date(Date.UTC(year + 1, 0, 1));
      query = query.gte("tanggal_masuk", from).lt("tanggal_masuk", toDate.toISOString().slice(0, 10));
    }
    if (pathway_type) query = query.eq("jenis_clinical_pathway", pathway_type);
    if (ward) query = query.eq("bangsal", ward);
    if (search) query = query.or(`nama_pasien.ilike.%${search}%,no_rm.ilike.%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, patients: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-patient.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.23.8";
var get_patient_default = defineTool2({
  name: "get_patient",
  title: "Detail pasien & kepatuhan",
  description: "Get one clinical pathway patient record together with its compliance data (kepatuhan CP, penunjang, terapi, sesuai target) and checklist items.",
  inputSchema: {
    patient_id: z2.string().optional().describe("Clinical pathway record UUID."),
    no_rm: z2.string().optional().describe("Medical record number; used when patient_id is not given.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ patient_id, no_rm }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!patient_id && !no_rm) {
      return { content: [{ type: "text", text: "Provide patient_id or no_rm" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let patientQuery = supabase.from("clinical_pathways").select("*").limit(1);
    patientQuery = patient_id ? patientQuery.eq("id", patient_id) : patientQuery.eq("no_rm", no_rm).order("tanggal_masuk", { ascending: false });
    const { data: patients, error } = await patientQuery;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const patient = patients?.[0];
    if (!patient) return { content: [{ type: "text", text: "Pasien tidak ditemukan" }], isError: true };
    const [{ data: compliance }, { data: checklist }] = await Promise.all([
      supabase.from("compliance_data").select("*").eq("patient_id", patient.id).maybeSingle(),
      supabase.from("clinical_pathway_checklist").select("*").eq("patient_id", patient.id)
    ]);
    const result = { patient, compliance: compliance ?? null, checklist: checklist ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/compliance-summary.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.23.8";
var compliance_summary_default = defineTool3({
  name: "compliance_summary",
  title: "Rekap kepatuhan clinical pathway",
  description: "Summarise clinical pathway compliance for a given year (optionally one pathway type): patient counts and percentage of kepatuhan CP, penunjang, terapi, and LOS sesuai target, broken down per month.",
  inputSchema: {
    year: z3.number().int().describe("Year of admission, e.g. 2026."),
    pathway_type: z3.string().optional().describe("Limit to one jenis clinical pathway.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ year, pathway_type }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("clinical_pathways").select("id, jenis_clinical_pathway, tanggal_masuk").gte("tanggal_masuk", `${year}-01-01`).lt("tanggal_masuk", `${year + 1}-01-01`);
    if (pathway_type) query = query.eq("jenis_clinical_pathway", pathway_type);
    const { data: patients, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const ids = (patients ?? []).map((p) => p.id);
    let compliance = [];
    if (ids.length) {
      const { data, error: cErr } = await supabase.from("compliance_data").select("patient_id, kepatuhan_cp, kepatuhan_penunjang, kepatuhan_terapi, sesuai_target").in("patient_id", ids);
      if (cErr) return { content: [{ type: "text", text: cErr.message }], isError: true };
      compliance = data ?? [];
    }
    const byPatient = new Map(compliance.map((c) => [c.patient_id, c]));
    const months = Array.from({ length: 12 }, (_, i) => ({
      month: i + 1,
      total: 0,
      kepatuhan_cp: 0,
      kepatuhan_penunjang: 0,
      kepatuhan_terapi: 0,
      sesuai_target: 0
    }));
    for (const p of patients ?? []) {
      const m = Number(String(p.tanggal_masuk).slice(5, 7));
      const row = months[m - 1];
      if (!row) continue;
      row.total += 1;
      const c = byPatient.get(p.id);
      if (c?.kepatuhan_cp) row.kepatuhan_cp += 1;
      if (c?.kepatuhan_penunjang) row.kepatuhan_penunjang += 1;
      if (c?.kepatuhan_terapi) row.kepatuhan_terapi += 1;
      if (c?.sesuai_target) row.sesuai_target += 1;
    }
    const pct = (n, d) => d ? Math.round(n / d * 1e3) / 10 : 0;
    const monthly = months.map((m) => ({
      ...m,
      kepatuhan_cp_pct: pct(m.kepatuhan_cp, m.total),
      kepatuhan_penunjang_pct: pct(m.kepatuhan_penunjang, m.total),
      kepatuhan_terapi_pct: pct(m.kepatuhan_terapi, m.total),
      sesuai_target_pct: pct(m.sesuai_target, m.total)
    }));
    const totals = months.reduce(
      (acc, m) => ({
        total: acc.total + m.total,
        kepatuhan_cp: acc.kepatuhan_cp + m.kepatuhan_cp,
        kepatuhan_penunjang: acc.kepatuhan_penunjang + m.kepatuhan_penunjang,
        kepatuhan_terapi: acc.kepatuhan_terapi + m.kepatuhan_terapi,
        sesuai_target: acc.sesuai_target + m.sesuai_target
      }),
      { total: 0, kepatuhan_cp: 0, kepatuhan_penunjang: 0, kepatuhan_terapi: 0, sesuai_target: 0 }
    );
    const result = {
      year,
      pathway_type: pathway_type ?? "semua",
      totals: {
        ...totals,
        kepatuhan_cp_pct: pct(totals.kepatuhan_cp, totals.total),
        kepatuhan_penunjang_pct: pct(totals.kepatuhan_penunjang, totals.total),
        kepatuhan_terapi_pct: pct(totals.kepatuhan_terapi, totals.total),
        sesuai_target_pct: pct(totals.sesuai_target, totals.total)
      },
      monthly
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-pathway-types.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_pathway_types_default = defineTool4({
  name: "list_pathway_types",
  title: "Daftar jenis clinical pathway",
  description: "List the clinical pathway types (jenis CP) configured in the app along with their LOS target in days.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("daftar_cp").select('id, jenis_cp, "Terget Los"').order("jenis_cp");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const types = (data ?? []).map((row) => ({
      id: row.id,
      jenis_cp: row.jenis_cp,
      target_los_hari: row["Terget Los"]
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(types, null, 2) }],
      structuredContent: { types }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "uxrgnwsdkkjrueoqozuq";
var mcp_default = defineMcp({
  name: "sipimu",
  title: "sipimu",
  version: "0.1.0",
  instructions: "Tools for SiPi-Mu, the clinical pathway reporting app of RS PKU Muhammadiyah Wonosobo. Use `list_pathway_types` to discover valid pathway names, `list_patients` to browse patient records, `get_patient` for one patient with its compliance and checklist, and `compliance_summary` for yearly/monthly kepatuhan statistics. All data is scoped to the signed-in user's permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_pathway_types_default, list_patients_default, get_patient_default, compliance_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
