// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmguilxweaxtezssjdqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtZ3VpbHh3ZWF4dGV6c3NqZHFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMjE0NzksImV4cCI6MjA2ODY5NzQ3OX0.VBQ4iUsuA0EjSLqwSntjAC-DcJ96eyTGj1nkqSzYTrU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});