// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxrgnwsdkkjrueoqozuq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4cmdud3Nka2tqcnVlb3FvenVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MTYwMDcsImV4cCI6MjA2ODk5MjAwN30.mRXkQ1ANvj5tPtVLLsgQSzdsfkCJJ29jGzVLUmPXJ2o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});